#!/bin/bash

if [ -n "$RANK0" ] ; then

  # send sshd to background
  /root/.ssh/entrypoint.sh &> /dev/null &

  # wait for other's sshd to startup
  if [ -z "$WAIT_SSHD_SECS" ] ; then
    WAIT_SSHD_SECS=60
  fi
  sleep $WAIT_SSHD_SECS

  if [ -z "$MPIRUN_FLAGS" ] ; then
    MPIRUN_FLAGS=""
  fi

  if [ -f /tmp/mpihosts ]; then
    MPIRUN_FLAGS="$MPIRUN_FLAGS --hostfile /tmp/mpihosts"
  elif [ -n "$HOSTS" ] ; then
    MPIRUN_FLAGS="$MPIRUN_FLAGS -H $HOSTS"
  else
    echo "Expecting HOSTS variable or /tmp/mpihosts file"
    exit 1
  fi

  mpirun \
    --allow-run-as-root \
    --mca plm_rsh_args "-p $SSHD_PORT" \
    $MPIRUN_FLAGS \
    $@

  if [ -z $SKIP_MPISTOP ]; then
    mpistop
  fi
else
  /root/.ssh/entrypoint.sh
fi

exit 0
