#!/bin/bash

if [ -n "$RANK0" ] ; then

  if [ -f /tmp/mpihosts ]; then
    MPIRUN_FLAGS="--hostfile /tmp/mpihosts"
  elif [ -n "$HOSTS" ] ; then
    MPIRUN_FLAGS="-H $HOSTS"
  else
    echo "Expecting HOSTS variable or /tmp/mpihosts file"
    exit 1
  fi

  mpirun \
    --allow-run-as-root \
    --mca plm_rsh_args "-p $SSHD_PORT" \
    $MPIRUN_FLAGS \
    service ssh stop &> /tmp/output
fi
